# # general settings
# name: finalmodel_production_train
# model_type: SRModel
# scale: 4
# num_gpu: 1 
# manual_seed: 0

# # dataset and data loader settings
# datasets:
#   train:
#     name: UAV_train_our
#     type: PairedImageDataset
#     # 路径锁定为你的 /root/ 目录
#     dataroot_gt: /root/SCINet/data/gttrain/img
#     dataroot_lq: /root/SCINet/data/lqtrain/img
#     io_backend:
#       type: disk

#     gt_size: 128
#     use_hflip: true
#     use_rot: true

#     # data loader
#     use_shuffle: true
#     num_worker_per_gpu: 3 
#     batch_size_per_gpu: 128 # 保持 16，若显存充足可改为 32
#     dataset_enlarge_ratio: 10 # 正式训练调回 100，极大提升读取速度
#     prefetch_mode: ~

#   val:
#     name: UAV_valid_our
#     type: PairedImageDataset
#     dataroot_gt: /root/SCINet/data/gtval/img
#     dataroot_lq: /root/SCINet/data/lqval/img
#     io_backend:
#       type: disk


# # network structures
# network_g:
#   type: SCINet
#   num_in_ch: 3
#   num_feat: 64
#   num_block: 8
#   num_out_ch: 3
#   upscale: 4
#   conv: BSConvU

# # path
# path:
#   pretrain_network_g: ~
#   strict_load_g: true
#   resume_state: ~ # 如果要接续之前的进度，请在此填入 .state 路径

# # training settings
# train:
#   optim_g:
#     type: Adam
#     lr: !!float 2e-4 # 正式训练建议稍微提高到 2e-4
#     weight_decay: 0
#     betas: [0.9, 0.999]

#   scheduler:
#     type: CosineAnnealingRestartLR
#     periods: [300000] # 对应总迭代次数
#     restart_weights: [1]
#     eta_min: !!float 1e-7


#   total_iter: 30000 # 正式训练设定为 30w 次
#   warmup_iter: -1 

#   # losses
#   pixel_opt:
#     type: L1Loss
#     loss_weight: 1.0
#     reduction: mean

# # validation settings
# val:
#   val_freq: !!float 500 # 每 5000 次验证一次，避免频繁验证拖慢速度
#   save_img: false # 正式训练建议关闭，节省磁盘空间

#   metrics:
#     psnr:
#       type: calculate_psnr
#       crop_border: 4
#       test_y_channel: false
#     ssim:
#       type: calculate_ssim
#       crop_border: 4
#       test_y_channel: false

# # logging settings
# logger:
#   print_freq: 200 # 每 200 次打印一次日志
#   save_checkpoint_freq: !!float 5000 # 每 5000 次保存一次模型
#   use_tb_logger: true
#   wandb:
#     project: ~
#     resume_id: ~
#     entity: ~

# # dist training settings
# # dist_params:
# #   backend: nccl
# #   port: 29500

# general settings
name: checkpoint_test_run
model_type: SRModel
scale: 4
num_gpu: 1 
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: UAV_train_our
    type: PairedImageDataset
    # [路径] 新机器训练集
    dataroot_gt: /mnt/workspace/SCINet/data/gttrain/img
    dataroot_lq: /mnt/workspace/SCINet/data/lqtrain/img
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8 
    batch_size_per_gpu: 128 
    dataset_enlarge_ratio: 100 
    prefetch_mode: ~

  val:
    name: UAV_valid_our
    type: PairedImageDataset
    # [路径] 继续使用 mini 验证集，保证验证速度
    dataroot_gt: /mnt/workspace/SCINet/data/gtval_mini/img
    dataroot_lq: /mnt/workspace/SCINet/data/lqval_mini/img
    io_backend:
      type: disk

# network structures
network_g:
  type: SCINet
  num_in_ch: 3
  num_feat: 64
  num_block: 8
  num_out_ch: 3
  upscale: 4
  conv: BSConvU

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  # [断点设置] 改为你刚才测试成功生成的最新 checkpoint 
  resume_state: /mnt/workspace/SCINet/experiments/checkpoint_test_run/training_states/40000.state
  
  # [实验根目录]
  experiments_root: /mnt/workspace/SCINet/experiments

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000  # 正式跑 30 万次
  warmup_iter: -1 

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000  # 恢复每 5000 次验证一次
  save_img: false
  pbar: true 

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 200        # 恢复每 200 次打印一次日志
  save_checkpoint_freq: !!float 5000 # 恢复每 5000 次保存一次权重
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~








